In [63]:
import numpy as np
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(device)

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

In [45]:
tensor = torch.rand(3, 4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.1585, 0.8701, 0.8872, 0.5774],
        [0.5249, 0.1395, 0.8584, 0.1601],
        [0.1348, 0.5196, 0.4462, 0.3051]])
torch.Size([3, 4])
torch.float32
cpu


In [11]:
tensor.reshape(2, 6)

tensor([[0.0037, 0.7010, 0.2494, 0.5635, 0.4145, 0.2571],
        [0.0095, 0.1168, 0.3159, 0.8195, 0.7460, 0.7873]], device='cuda:0')

In [12]:
tensor

tensor([[0.0037, 0.7010, 0.2494, 0.5635],
        [0.4145, 0.2571, 0.0095, 0.1168],
        [0.3159, 0.8195, 0.7460, 0.7873]], device='cuda:0')

In [67]:
weights = torch.randn(1, 2)
print(weights.T)
print(weights.T.shape)

tensor([[-0.3028],
        [-0.6326]])
torch.Size([2, 1])


In [56]:
features = torch.randn(3, 2)
features

tensor([[-0.8228, -0.7872],
        [ 0.7474,  1.4207],
        [-0.4824, -1.2616]])

In [62]:
torch.mm(features, weights.T)

tensor([[ 1.1355],
        [-1.2660],
        [ 0.9317]])

In [65]:
x = features.numpy()
w = weights.numpy()

np.dot(x, w.T)


array([[ 1.1355042 ],
       [-1.2659698 ],
       [ 0.93168855]], dtype=float32)