In [2]:
import torch

# Check if PyTorch is installed
print("PyTorch version:", torch.__version__)

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available. Device count:", torch.cuda.device_count())
    print("Current CUDA device:", torch.cuda.current_device())
    print("CUDA device name:", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available.")

PyTorch version: 2.5.1+cu118
CUDA is available. Device count: 1
Current CUDA device: 0
CUDA device name: NVIDIA GeForce RTX 2070 SUPER


In [3]:
print(torch.cuda.is_available())

True


In [4]:
# Ali uses autocomplete: 
# "continue" extension 
# api "codestral"


In [5]:
torch.randn(3)

tensor([ 0.7534, -2.0590, -0.5366])

In [6]:
dimension_1 = 2  # num rows
dimension_2 = 3  # num columns

my_tensor = torch.randn(dimension_1, dimension_2)

print(my_tensor)
print(my_tensor.shape)

tensor([[-1.5192,  1.3407,  0.4330],
        [ 0.2190, -0.0416,  0.0091]])
torch.Size([2, 3])


In [7]:
dimension_1 = 3  # depth (number of layers)
dimension_2 = 3  # height (number of rows)
dimension_3 = 2  # width (number of columns)

my_tensor_3d = torch.randn(dimension_1, dimension_2, dimension_3)

print(my_tensor_3d)
print(my_tensor_3d.shape)

tensor([[[-0.8258, -1.1258],
         [-1.7696,  1.5265],
         [ 0.2818, -0.9865]],

        [[-0.6463,  1.4097],
         [-1.4645, -0.5203],
         [ 0.2217, -2.0691]],

        [[-0.5328,  0.9948],
         [ 0.7522,  0.0973],
         [ 0.1958,  0.5230]]])
torch.Size([3, 3, 2])


In [8]:
a_tensor = torch.tensor([1, 2, 3, 4, 5])
another_tensor = torch.tensor([9, 9, 9, 9, 9])
print(a_tensor)
print(another_tensor)
print(a_tensor + another_tensor)  # vector like addition
print(a_tensor * another_tensor)  # vector like multiplication

tensor([1, 2, 3, 4, 5])
tensor([9, 9, 9, 9, 9])
tensor([10, 11, 12, 13, 14])
tensor([ 9, 18, 27, 36, 45])


In [22]:
my_tensor_3d

tensor([[[-0.8258, -1.1258],
         [-1.7696,  1.5265],
         [ 0.2818, -0.9865]],

        [[-0.6463,  1.4097],
         [-1.4645, -0.5203],
         [ 0.2217, -2.0691]],

        [[-0.5328,  0.9948],
         [ 0.7522,  0.0973],
         [ 0.1958,  0.5230]]])

In [31]:
my_tensor_3d[2].size()

torch.Size([3, 2])

In [25]:
print(my_tensor_3d[0])
print(my_tensor_3d[0].shape)
print(my_tensor_3d[0].shape[0])

tensor([[-0.8258, -1.1258],
        [-1.7696,  1.5265],
        [ 0.2818, -0.9865]])
torch.Size([3, 2])
3


In [12]:
my_tensor_3d.reshape(-1, 1)

tensor([[-0.8258],
        [-1.1258],
        [-1.7696],
        [ 1.5265],
        [ 0.2818],
        [-0.9865],
        [-0.6463],
        [ 1.4097],
        [-1.4645],
        [-0.5203],
        [ 0.2217],
        [-2.0691],
        [-0.5328],
        [ 0.9948],
        [ 0.7522],
        [ 0.0973],
        [ 0.1958],
        [ 0.5230]])