In [1]:
import torch

# Check if PyTorch is installed
print("PyTorch version:", torch.__version__)

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available. Device count:", torch.cuda.device_count())
    print("Current CUDA device:", torch.cuda.current_device())
    print("CUDA device name:", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available.")

PyTorch version: 2.5.1+cu118
CUDA is available. Device count: 1
Current CUDA device: 0
CUDA device name: NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [9]:
print(torch.cuda.is_available())

True


In [ ]:
# Ali uses autocomplete: view codestral

In [13]:
torch.randn(3)

tensor([-0.0577,  0.1037,  0.7738])

In [11]:
dimension_1 = 2  # num rows
dimension_2 = 3  # num columns

my_tensor = torch.randn(dimension_1, dimension_2)

print(my_tensor)
print(my_tensor.shape)

tensor([[ 0.5404,  0.5481, -0.7768],
        [-0.3593, -0.3514, -1.0757]])
torch.Size([2, 3])


In [7]:
dimension_1 = 3  # depth (number of layers)
dimension_2 = 3  # height (number of rows)
dimension_3 = 2  # width (number of columns)

my_tensor_3d = torch.randn(dimension_1, dimension_2, dimension_3)

print(my_tensor_3d)
print(my_tensor_3d.shape)

tensor([[[ 0.5608, -0.2213],
         [-2.2349,  0.5160],
         [-0.4247,  0.4856]],

        [[-1.3950, -0.6643],
         [ 0.4949,  0.8759],
         [-0.6792, -1.5798]],

        [[-0.4681,  0.3512],
         [ 0.5568,  0.5850],
         [-0.3484,  0.6290]]])
torch.Size([3, 3, 2])


In [15]:
a_tensor = torch.tensor([1, 2, 3, 4, 5])
another_tensor = torch.tensor([9, 9, 9, 9, 9])
print(a_tensor)
print(another_tensor)
print(a_tensor + another_tensor)  # vector like addition
print(a_tensor * another_tensor)  # vector like multiplication

tensor([1, 2, 3, 4, 5])
tensor([9, 9, 9, 9, 9])
tensor([10, 11, 12, 13, 14])
tensor([ 9, 18, 27, 36, 45])
